/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VIEW;

import DTO.Alnuo;
import javax.swing.JOptionPane;

/**
 *
 * @author aluno.saolucas
 */
public class FormularioAluno extends javax.swing.JFrame {

    /**
     * Creates new form FormularioAluno
     */
    public FormularioAluno() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCPF1 = new javax.swing.JLabel();
        lblIdade1 = new javax.swing.JLabel();
        txtCPF1 = new javax.swing.JTextField();
        txtIdade1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        lblEmail1 = new javax.swing.JLabel();
        btnEnviar1 = new javax.swing.JButton();
        lblTelefone1 = new javax.swing.JLabel();
        btnProfessor1 = new javax.swing.JButton();
        lblCEP1 = new javax.swing.JLabel();
        lblRG1 = new javax.swing.JLabel();
        btnPessoa = new javax.swing.JButton();
        txtEmail1 = new javax.swing.JTextField();
        lblNome1 = new javax.swing.JLabel();
        txtTelefone1 = new javax.swing.JTextField();
        txtNome1 = new javax.swing.JTextField();
        txtRG1 = new javax.swing.JTextField();
        txtSobrenome1 = new javax.swing.JTextField();
        txtCEP1 = new javax.swing.JTextField();
        lblSobrenome1 = new javax.swing.JLabel();
        lblIdade2 = new javax.swing.JLabel();
        txtcurso = new javax.swing.JTextField();
        txtnumeromatricula = new javax.swing.JTextField();
        lblIdade3 = new javax.swing.JLabel();
        txtresponsavel = new javax.swing.JTextField();
        lblIdade4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Formulario do Aluno");
        setResizable(false);

        lblCPF1.setText("CPF:");

        lblIdade1.setText("Idade:");

        jLabel3.setText("Formulário de cadastro");

        lblEmail1.setText("Email:");

        btnEnviar1.setText("Enviar");
        btnEnviar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviar1ActionPerformed(evt);
            }
        });

        lblTelefone1.setText("Telefone:");

        btnProfessor1.setText("Professor");

        lblCEP1.setText("CEP:");

        lblRG1.setText("RG:");

        btnPessoa.setText("Pessoa");

        lblNome1.setText("Nome:");

        lblSobrenome1.setText("Sobrenome:");

        lblIdade2.setText("Curso:");

        lblIdade3.setText("N° de Matrícula:");

        lblIdade4.setText("Responsável:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblEmail1)
                                    .addComponent(lblTelefone1)
                                    .addComponent(lblCEP1)
                                    .addComponent(lblRG1)
                                    .addComponent(lblCPF1)
                                    .addComponent(btnProfessor1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblIdade1)
                                        .addGap(43, 43, 43)))
                                .addComponent(lblIdade2))
                            .addComponent(lblSobrenome1)
                            .addComponent(lblNome1)
                            .addComponent(lblIdade3)
                            .addComponent(lblIdade4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtEmail1, javax.swing.GroupLayout.DEFAULT_SIZE, 364, Short.MAX_VALUE)
                            .addComponent(txtCPF1)
                            .addComponent(txtIdade1)
                            .addComponent(txtTelefone1)
                            .addComponent(txtNome1)
                            .addComponent(txtCEP1)
                            .addComponent(txtSobrenome1)
                            .addComponent(txtRG1)
                            .addComponent(txtcurso)
                            .addComponent(txtnumeromatricula, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtresponsavel, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(197, 197, 197)
                .addComponent(btnEnviar1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                .addComponent(btnPessoa)
                .addGap(59, 59, 59))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome1)
                    .addComponent(txtEmail1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCPF1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSobrenome1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdade1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEmail1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTelefone1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTelefone1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNome1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCEP1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCEP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRG1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSobrenome1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCPF1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRG1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIdade1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIdade2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnumeromatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIdade3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtresponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIdade4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEnviar1)
                    .addComponent(btnPessoa)
                    .addComponent(btnProfessor1))
                .addGap(15, 15, 15))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnviar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviar1ActionPerformed
        Alnuo objAlunoDTO = new Alnuo(txtNome1.getText(), txtSobrenome1.getText(), txtEmail1.getText(),
                txtTelefone1.getText(), txtCEP1.getText(), txtCPF1.getText(), txtRG1.getText(),
                Integer.parseInt(txtIdade1.getText()), txtnumeromatricula.getText(), txtcurso.getText(),
                txtresponsavel.getText());
        
        JOptionPane.showMessageDialog(rootPane, objAlunoDTO.toString());
    }//GEN-LAST:event_btnEnviar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormularioAluno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnviar1;
    private javax.swing.JButton btnPessoa;
    private javax.swing.JButton btnProfessor1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblCEP1;
    private javax.swing.JLabel lblCPF1;
    private javax.swing.JLabel lblEmail1;
    private javax.swing.JLabel lblIdade1;
    private javax.swing.JLabel lblIdade2;
    private javax.swing.JLabel lblIdade3;
    private javax.swing.JLabel lblIdade4;
    private javax.swing.JLabel lblNome1;
    private javax.swing.JLabel lblRG1;
    private javax.swing.JLabel lblSobrenome1;
    private javax.swing.JLabel lblTelefone1;
    private javax.swing.JTextField txtCEP1;
    private javax.swing.JTextField txtCPF1;
    private javax.swing.JTextField txtEmail1;
    private javax.swing.JTextField txtIdade1;
    private javax.swing.JTextField txtNome1;
    private javax.swing.JTextField txtRG1;
    private javax.swing.JTextField txtSobrenome1;
    private javax.swing.JTextField txtTelefone1;
    private javax.swing.JTextField txtcurso;
    private javax.swing.JTextField txtnumeromatricula;
    private javax.swing.JTextField txtresponsavel;
    // End of variables declaration//GEN-END:variables
}
